#!/bin/bash

if [ "$DATABASE_ENGINE" = "timescale.db.backends.postgresql" ]
then
    echo "Waiting for postgres..."

    while ! nc -z db 5432; do
      sleep 0.1
    done

    echo "PostgreSQL started for test_clickhouse!"
fi

# Ожидание ClickHouse
echo "Waiting for Quotes DB..."

while ! nc -z quotes_db 8123; do
  sleep 0.1
done

echo "ClickHouse started!"

exec "$@"
