#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate_clickhouse
python manage.py migrate
python manage.py collectstatic --noinput
exec gunicorn config.wsgi:application --bind 0.0.0.0:8009 --reload --workers 10
# python manage.py runserver 0.0.0.0:8009
