version: '3.3'

volumes:
  local_db_data:
  static_volume:

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - ./apps:/backup_manager/apps
      - ./locale:/backup_manager/locale
      - ./static:/backup_manager/static
      - local_db_data:/backup_manager/database
      - static_volume:/backup_manager/static
    ports:
      - "81:80"
    env_file:
      - .envs/.django
    restart: on-failure