version: '3.7'

volumes:
  postgres_data:
  clickhouse_data:

services:
  db:
    image: postgres:13.12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
    ports:
      - "5438:5432"

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_DB: qrm_notification
      CLICKHOUSE_USER: clickhouse-user
      CLICKHOUSE_PASSWORD: secret
      CLICKHOUSE_LOG: /var/log/clickhouse-server/clickhouse-server.log
      CLICKHOUSE_INIT_TIMEOUT: 60
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  