version: '3.3'

volumes:
  local_db_data:
  static_volume:

services:
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/nginx/Dockerfile
  #   ports:
  #     - 81:80
  #   depends_on:
  #     - web
  #   volumes:
  #     - static_volume:/backup_manager/static
  #   restart: on-failure

  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      # - ./apps:/traderhub # только для локальной разработки
      - local_db_data:/backup_manager/database
      - static_volume:/backup_manager/static
    ports:
      - "81:80" # gunicorn
      - "8009:8009" # gunicorn
    env_file:
      - .envs/.django
    restart: on-failure