# Generated by Django 5.1.3 on 2024-11-14 15:20
import os

from django.db import migrations


def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    username = os.getenv("ADMIN_USER", "admin")
    password = os.getenv("ADMIN_PASSWORD", "admin")

    if username and password:
        User.objects.create_superuser(username=username, password=password)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
