# Generated by Django 5.1.3 on 2024-11-14 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3FileStorage',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('host', models.URLField(max_length=300, verbose_name='Host(https://host/')),
                ('access_key', models.CharField(max_length=300, verbose_name='Access Key')),
                ('secret_key', models.CharField(max_length=300, verbose_name='Secret Key')),
            ],
            options={
                'verbose_name': 'S3 File Storage',
                'verbose_name_plural': 'S3 File Storages',
            },
        ),
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('db_type', models.IntegerField(choices=[(1, 'Postgres'), (2, 'ClickHouse')], verbose_name='Type')),
                ('connection_string', models.TextField(verbose_name='Connection Link')),
            ],
            options={
                'verbose_name': 'Database',
                'verbose_name_plural': 'Databases',
            },
        ),
    ]
