# Generated by Django 5.1.3 on 2024-11-14 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpTask',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('task_period', models.IntegerField(choices=[(1, 'Never'), (2, 'Every day'), (3, 'Every week'), (4, 'Every month')], verbose_name='Task Period')),
                ('max_dumpfiles_keep', models.PositiveIntegerField(default=1, verbose_name='Max Dump files count to keep')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.userdatabase')),
                ('file_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.s3filestorage')),
            ],
            options={
                'verbose_name': 'Dump Task',
                'verbose_name_plural': 'Dump Tasks',
            },
        ),
        migrations.CreateModel(
            name='DumpTaskOperation',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'In Process'), (3, 'Fail'), (4, 'Success')], default=1, verbose_name='Status')),
                ('error_text', models.TextField(blank=True, default=None, null=True, verbose_name='Error text')),
                ('dump_path', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Dump File Path')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.dumptask')),
            ],
            options={
                'verbose_name': 'Dump Task Operation',
                'verbose_name_plural': 'Dump Tasks Operations',
            },
        ),
        migrations.CreateModel(
            name='RecoverBackupOperation',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'In Process'), (3, 'Fail'), (4, 'Success')], default=1, verbose_name='Status')),
                ('error_text', models.TextField(blank=True, default=None, null=True, verbose_name='Error text')),
                ('dump_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.dumptaskoperation')),
            ],
            options={
                'verbose_name': 'Recover Backup Operation',
                'verbose_name_plural': 'Recover Backup Operations',
            },
        ),
    ]
