# Generated by Django 5.1.3 on 2024-11-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_dumptask_dumptaskoperation_recoverbackupoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3filestorage',
            name='bucket_name',
            field=models.CharField(default='', max_length=300, verbose_name='Bucket Name'),
        ),
    ]
