# Generated by Django 5.2.7 on 2025-10-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_s3filestorage_bucket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('s3', 'S3'), ('yadisk', 'Yandex Disk')], default='s3', max_length=10)),
                ('host', models.URLField(blank=True, help_text='S3 endpoint (для S3). Для Yandex Disk можно оставить пустым', null=True)),
                ('bucket_name', models.CharField(blank=True, help_text='S3 bucket (для S3). Для Yandex Disk не используется', max_length=255, null=True)),
                ('access_key', models.CharField(blank=True, help_text='S3 Access Key (для S3)', max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, help_text='S3 Secret Key ИЛИ OAuth-токен (для Yandex Disk)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File storage',
                'verbose_name_plural': 'File storages',
            },
        ),
        migrations.AlterModelOptions(
            name='dumptask',
            options={'verbose_name': 'Задача на дамп', 'verbose_name_plural': 'Задачи на дамп'},
        ),
        migrations.AlterModelOptions(
            name='dumptaskoperation',
            options={'verbose_name': 'Операция дампа', 'verbose_name_plural': 'Операции дампа'},
        ),
        migrations.AlterModelOptions(
            name='recoverbackupoperation',
            options={'verbose_name': 'Операция восстановления', 'verbose_name_plural': 'Операции восстановления'},
        ),
        migrations.AlterModelOptions(
            name='userdatabase',
            options={'verbose_name': 'База данных', 'verbose_name_plural': 'Базы данных'},
        ),
        migrations.AlterField(
            model_name='dumptask',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='dumptask',
            name='max_dumpfiles_keep',
            field=models.PositiveIntegerField(default=1, verbose_name='Макс. количество дампов для хранения'),
        ),
        migrations.AlterField(
            model_name='dumptask',
            name='task_period',
            field=models.IntegerField(choices=[(1, 'Никогда'), (2, 'Каждый день'), (3, 'Каждую неделю'), (4, 'Каждый месяц')], verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='dumptask',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='dump_path',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Путь к файлу дампа'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='error_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Создана'), (2, 'В процессе'), (3, 'Провал'), (4, 'Успешно')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='dumptaskoperation',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='recoverbackupoperation',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='recoverbackupoperation',
            name='error_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='recoverbackupoperation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Создана'), (2, 'В процессе'), (3, 'Провал'), (4, 'Успешно')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='recoverbackupoperation',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='connection_string',
            field=models.TextField(verbose_name='Ссылка подключения'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='db_type',
            field=models.IntegerField(choices=[(1, 'Postgres'), (2, 'ClickHouse')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='dumptask',
            name='file_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.filestorage'),
        ),
        migrations.DeleteModel(
            name='S3FileStorage',
        ),
    ]